<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.21">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>9&nbsp; Sampling – Principles and Techniques of Data Science</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../modeling_slr/modeling_slr.html" rel="next">
<link href="../visualization_2/visualization_2.html" rel="prev">
<link href="../data100_logo.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ea1d7ac60288e0f1efdbc993fd8432ae.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-48faffd076f6e246ab7435acea77d2f2.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../sampling/sampling.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Sampling</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../data100_logo.png" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="../data100_logo.png" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Principles and Techniques of Data Science</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/DS-100/course-notes" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intro_lec/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pandas_1/pandas_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Pandas I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pandas_2/pandas_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Pandas II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pandas_3/pandas_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Pandas III</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../eda/eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data Cleaning and EDA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regex/regex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Regular Expressions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../visualization_1/visualization_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Visualization I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../visualization_2/visualization_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Visualization II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sampling/sampling.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Sampling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../modeling_slr/modeling_slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Modeling &amp; SLR</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../constant_model_loss_transformations/loss_transformations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Constant Model, Loss, and Transformations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ols/ols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Ordinary Least Squares</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../case_study_HCE/case_study_HCE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Case Study in Human Contexts and Ethics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../gradient_descent/gradient_descent.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">sklearn and Gradient Descent</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../feature_engineering/feature_engineering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Gradient Descent Continuation, Feature Engineering (Summer 2025)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cv_regularization/cv_reg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Cross Validation and Regularization (Summer 2025)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../probability_1/probability_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Random Variables (Summer 2025)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../probability_2/probability_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Estimators, Bias, and Variance (Summer 2025)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../inference_causality/inference_causality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Parameter Inference and Bootstrapping (Summer 2025)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sql_I/sql_I.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">SQL I (Summer 2025)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sql_II/sql_II.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">SQL II (Summer 2025)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../logistic_regression_1/logistic_reg_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Logistic Regression I (Summer 2025)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../logistic_regression_2/logistic_reg_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Logistic Regression II (Summer 2025)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pca_1/pca_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">PCA I (Summer 2025)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../pca_2/pca_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">PCA II (Summer 2025)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../clustering/clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Clustering (Summer 2025)</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#censuses-and-surveys" id="toc-censuses-and-surveys" class="nav-link active" data-scroll-target="#censuses-and-surveys"><span class="header-section-number">9.1</span> Censuses and Surveys</a></li>
  <li><a href="#sampling-a-case-study" id="toc-sampling-a-case-study" class="nav-link" data-scroll-target="#sampling-a-case-study"><span class="header-section-number">9.2</span> Sampling: A Case Study</a></li>
  <li><a href="#sampling-errors" id="toc-sampling-errors" class="nav-link" data-scroll-target="#sampling-errors"><span class="header-section-number">9.3</span> Sampling Errors</a></li>
  <li><a href="#types-of-sampling" id="toc-types-of-sampling" class="nav-link" data-scroll-target="#types-of-sampling"><span class="header-section-number">9.4</span> Types of Sampling</a>
  <ul>
  <li><a href="#example-scheme-1-probability-sample" id="toc-example-scheme-1-probability-sample" class="nav-link" data-scroll-target="#example-scheme-1-probability-sample"><span class="header-section-number">9.4.1</span> Example Scheme 1: Probability Sample</a></li>
  <li><a href="#example-scheme-2-simple-random-sample" id="toc-example-scheme-2-simple-random-sample" class="nav-link" data-scroll-target="#example-scheme-2-simple-random-sample"><span class="header-section-number">9.4.2</span> Example Scheme 2: Simple Random Sample?</a></li>
  <li><a href="#example-scheme-3-stratified-random-sampling" id="toc-example-scheme-3-stratified-random-sampling" class="nav-link" data-scroll-target="#example-scheme-3-stratified-random-sampling"><span class="header-section-number">9.4.3</span> Example Scheme 3: Stratified Random Sampling</a></li>
  </ul></li>
  <li><a href="#non-representative-sampling-and-post-stratification" id="toc-non-representative-sampling-and-post-stratification" class="nav-link" data-scroll-target="#non-representative-sampling-and-post-stratification"><span class="header-section-number">9.5</span> Non-representative Sampling and Post-stratification</a>
  <ul>
  <li><a href="#example-non-representative-sampling-scheme" id="toc-example-non-representative-sampling-scheme" class="nav-link" data-scroll-target="#example-non-representative-sampling-scheme"><span class="header-section-number">9.5.1</span> Example: Non-representative Sampling Scheme</a></li>
  </ul></li>
  <li><a href="#demo-the-1936-presidential-election-results" id="toc-demo-the-1936-presidential-election-results" class="nav-link" data-scroll-target="#demo-the-1936-presidential-election-results"><span class="header-section-number">9.6</span> Demo: The 1936 Presidential Election Results</a>
  <ul>
  <li><a href="#simple-random-sample-srs" id="toc-simple-random-sample-srs" class="nav-link" data-scroll-target="#simple-random-sample-srs"><span class="header-section-number">9.6.1</span> 🎩 Simple Random Sample (SRS)</a></li>
  </ul></li>
  <li><a href="#demo-revisiting-the-1936-literary-digest-poll" id="toc-demo-revisiting-the-1936-literary-digest-poll" class="nav-link" data-scroll-target="#demo-revisiting-the-1936-literary-digest-poll"><span class="header-section-number">9.7</span> Demo: Revisiting the 1936 Literary Digest Poll</a>
  <ul>
  <li><a href="#post-stratification-with-literary-digest-responses-from-1932-and-1936" id="toc-post-stratification-with-literary-digest-responses-from-1932-and-1936" class="nav-link" data-scroll-target="#post-stratification-with-literary-digest-responses-from-1932-and-1936"><span class="header-section-number">9.7.1</span> 🥞 Post-stratification with Literary Digest responses from 1932 and 1936</a></li>
  </ul></li>
  <li><a href="#bonus-follow-up-improvements" id="toc-bonus-follow-up-improvements" class="nav-link" data-scroll-target="#bonus-follow-up-improvements"><span class="header-section-number">9.8</span> 🎁 Bonus: Follow Up Improvements</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">9.9</span> Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Sampling</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Learning Outcomes
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<ul>
<li>Understand how to appropriately collect data to help answer a question.</li>
</ul>
</div>
</div>
</div>
<p>In data science, understanding characteristics of a population starts with having quality data to investigate. While it is often impossible to collect all the data describing a population, we can overcome this by properly sampling from the population. In this note, we will discuss appropriate techniques for sampling from populations.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/data_life_cycle_sampling.png" class="img-fluid figure-img"></p>
<figcaption>Lifecycle diagram</figcaption>
</figure>
</div>
<section id="censuses-and-surveys" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="censuses-and-surveys"><span class="header-section-number">9.1</span> Censuses and Surveys</h2>
<p>In general: a <strong>census</strong> is “a complete count or survey of a <strong>population</strong>, typically recording various details of <strong>individuals</strong>.” An example is the U.S. Decennial Census which was held in April 2020. It counts <em>every person</em> living in all 50 states, DC, and US territories, not just citizens. Participation is required by law (it is mandated by the U.S. Constitution). Important uses include the allocation of Federal funds, congressional representation, and drawing congressional and state legislative districts. The census is composed of a <strong>survey</strong> mailed to different housing addresses in the United States.</p>
<p>A <strong>survey</strong> is a set of questions. An example is workers sampling individuals and households. What is asked and how it is asked can affect how the respondent answers or even whether or not they answer in the first place.</p>
<p>While censuses are great, it is often very difficult and expensive to survey everyone in a population. Imagine the amount of resources, money, time, and energy the U.S. spent on the 2020 Census. While this does give us more accurate information about the population, it’s often infeasible to execute. Thus, we usually survey a subset of the population instead.</p>
<p>A <strong>sample</strong> is (usually) a subset of the population that is often used to make inferences about the population. If our sample is a good representation of our population, then we can use it to glean useful information at a lower cost. That being said, how the sample is drawn will affect the reliability of such inferences. Two common sources of error in sampling are <strong>chance error</strong>, where random samples can vary from what is expected in any direction, and <strong>bias</strong>, which is a systematic error in one direction. Biases can be the result of many things, for example, our sampling scheme or survey methods.</p>
<p>Let’s define some useful vocabulary:</p>
<ul>
<li><strong>Population</strong>: The group that you want to learn something about.
<ul>
<li><strong>Individuals</strong> in a population are not always people. Other populations include bacteria in your gut (sampled using DNA sequencing), trees of a certain species, small businesses receiving a microloan, or published results in an academic journal or field.</li>
</ul></li>
<li><strong>Sampling Frame</strong>: The list from which the sample is drawn.
<ul>
<li>For example, if sampling people, then the sampling frame is the set of all people that could possibly end up in your sample.</li>
</ul></li>
<li><strong>Sample</strong>: Who you actually end up sampling. The sample is therefore a subset of your <em>sampling frame</em>.</li>
</ul>
<p>While ideally, these three sets would be exactly the same, they usually aren’t in practice. For example, there may be individuals in your sampling frame (and hence, your sample) that are not in your population. And generally, sample sizes are much smaller than population sizes.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/samplingframe.png" class="img-fluid figure-img"></p>
<figcaption>Sampling_Frames</figcaption>
</figure>
</div>
</section>
<section id="sampling-a-case-study" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="sampling-a-case-study"><span class="header-section-number">9.2</span> Sampling: A Case Study</h2>
<p>The following case study is adapted from <em>Statistics</em> by Freedman, Pisani, and Purves, W.W. Norton NY, 1978.</p>
<p>In 1936, President Franklin D. Roosevelt (Democratic) went up for re-election against Alf Landon (Republican). As is usual, <strong>polls</strong> were conducted in the months leading up to the election to try and predict the outcome. The <em>Literary Digest</em> was a magazine that had successfully predicted the outcome of 5 general elections coming into 1936. In their polling for the 1936 election, they sent out their survey to 10 million individuals whom they found from phone books, lists of magazine subscribers, and lists of country club members. Of the roughly 2.4 million people who filled out the survey, only 43% reported they would vote for Roosevelt; thus, the <em>Digest</em> predicted that Landon would win.</p>
<p>On election day, Roosevelt won in a landslide, winning 61% of the popular vote of about 45 million voters. How could the <em>Digest</em> have been so wrong with their polling?</p>
<p>It turns out that the <em>Literary Digest</em> sample was not representative of the population. Their sampling frame of people found in phone books, lists of magazine subscribers, and lists of country club members were more affluent and tended to vote Republican. As such, their sampling frame was inherently skewed in Landon’s favor. The <em>Literary Digest</em> completely overlooked the lion’s share of voters who were still suffering through the Great Depression. Furthermore, they had a dismal response rate (about 24%); who knows how the other non-respondents would have polled? The <em>Digest</em> folded just 18 months after this disaster.</p>
<p>At the same time, George Gallup, a rising statistician, also made predictions about the 1936 elections. Despite having a smaller sample size of “only” 50,000 (this is still more than necessary; more on this when we cover the Central Limit Theorem), his estimate that 56% of voters would choose Roosevelt was much closer to the actual result (61%). Gallup also predicted the <em>Digest</em>’s prediction within 1% with a sample size of only 3000 people by anticipating the <em>Digest</em>’s affluent sampling frame and subsampling those individuals.</p>
</section>
<section id="sampling-errors" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="sampling-errors"><span class="header-section-number">9.3</span> Sampling Errors</h2>
<p>So what’s the moral of the story? Samples, while convenient, are subject to chance error and <strong>bias</strong>. Election polling, in particular, can involve many sources of bias. To name a few:</p>
<ul>
<li><strong>Selection bias</strong> systematically excludes (or favors) particular groups.
<ul>
<li>Example: the Literary Digest poll excludes people not in phone books.</li>
<li>How to avoid: Randomly sample, and improve overlap of sampling frame and population.</li>
</ul></li>
<li><strong>Response/Measurement bias</strong> occurs because people don’t always respond truthfully. Survey designers pay special detail to the nature and wording of questions to avoid this type of bias.
<ul>
<li>Example: Illegal immigrants might not answer truthfully when asked citizenship questions on the census survey.</li>
<li>How to avoid: Improve questions. Lots of response bias <a href="https://en.wikipedia.org/wiki/Response_bias#:~:text=%5B7%5D-,Types,-%5Bedit%5D">subtypes + prevention methods</a>.</li>
</ul></li>
<li><strong>Non-response bias</strong> occurs because people don’t always respond to survey requests, which can skew responses.
<ul>
<li>Example: Only 2.4m out of 10m people responded to the <em>Literary Digest</em>’s poll.</li>
<li>How to avoid: Increase response rate. For example, reduce the number and length of questions, incentivize completion, and follow up.</li>
</ul></li>
</ul>
</section>
<section id="types-of-sampling" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="types-of-sampling"><span class="header-section-number">9.4</span> Types of Sampling</h2>
<p>When sampling, it is essential to focus on the quality of the sample rather than the quantity of the sample. A huge sample size does not fix a bad sampling method. Our main goal is to gather a sample that is representative of the population it came from. In this section, we’ll explore the different types of sampling and their pros and cons.</p>
<p>A <strong>convenience sample</strong> is whatever you can get ahold of; this type of sampling is <em>non-random</em>. Note that haphazard sampling is not necessarily random sampling; there are many potential sources of bias.</p>
<p>In a <strong>probability sample</strong>, we provide the <strong>chance</strong> that any specified <strong>set</strong> of individuals will be in the sample (individuals in the population can have different chances of being selected; they don’t all have to be uniform), and we sample at random based off this known chance. For this reason, probability samples are also called <strong>random samples</strong>. The randomness provides a few benefits:</p>
<ul>
<li>Because we know the source probabilities, we can <strong>measure the errors</strong>.</li>
<li>Sampling at random gives us a more representative sample of the population, which <strong>reduces bias</strong>. (Note: this is only the case when the probability distribution we’re sampling from is accurate. Random samples using “bad” or inaccurate distributions can produce biased estimates of population quantities.)</li>
<li>Probability samples allow us to <strong>estimate</strong> the <strong>bias</strong> and <strong>chance error</strong>, which helps us <strong>quantify uncertainty</strong> (more in a future lecture).</li>
</ul>
<p>The real world is usually more complicated, and we often don’t know the initial probabilities. For example, we do not generally know the probability that a given bacterium is in a microbiome sample or whether people will answer when Gallup calls landlines. That being said, still we try to model probability sampling to the best of our ability even when the sampling or measurement process is not fully under our control.</p>
<p>A few common random sampling schemes:</p>
<ul>
<li>A <strong>uniform random sample with replacement</strong> is a sample drawn <strong>uniformly</strong> at random <strong>with</strong> replacement.
<ul>
<li>Random doesn’t always mean “uniformly at random,” but in this specific context, it does.</li>
<li>Some individuals in the population might get picked more than once.</li>
</ul></li>
<li>A <strong>simple random sample (SRS)</strong> is a sample drawn <strong>uniformly</strong> at random <strong>without</strong> replacement.
<ul>
<li>Every individual (and subset of individuals) has the same chance of being selected from the sampling frame.</li>
<li>Every pair has the same chance as every other pair.</li>
<li>Every triple has the same chance as every other triple.</li>
<li>And so on.</li>
</ul></li>
<li>A <strong>stratified random sample</strong>, where the sampling frame is divided into non-overlapping <strong>strata</strong> according to chosen characteristics. Then, a simple random sample (SRS) is conducted on each <strong>stratum</strong>, with sample size proportional to stratum size.</li>
</ul>
<section id="example-scheme-1-probability-sample" class="level3" data-number="9.4.1">
<h3 data-number="9.4.1" class="anchored" data-anchor-id="example-scheme-1-probability-sample"><span class="header-section-number">9.4.1</span> Example Scheme 1: Probability Sample</h3>
<p>Suppose we have 3 TA’s (<strong>A</strong>rman, <strong>B</strong>oyu, <strong>C</strong>harlie): I decide to sample 2 of them as follows:</p>
<ul>
<li>I choose A with probability 1.0</li>
<li>I choose either B or C, each with a probability of 0.5.</li>
</ul>
<p>We can list all the possible outcomes and their respective probabilities in a table:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Outcome</th>
<th>Probability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>{A, B}</td>
<td>0.5</td>
</tr>
<tr class="even">
<td>{A, C}</td>
<td>0.5</td>
</tr>
<tr class="odd">
<td>{B, C}</td>
<td>0</td>
</tr>
</tbody>
</table>
<p>This is a <strong>probability sample</strong> (though not a great one). Of the 3 people in my population, I know the chance of getting each subset. Suppose I’m measuring the average distance TAs live from campus.</p>
<ul>
<li>This scheme does not see the entire population!</li>
<li>My estimate using the single sample I take has some chance error depending on if I see AB or AC.</li>
<li>This scheme is biased towards A’s response.</li>
</ul>
</section>
<section id="example-scheme-2-simple-random-sample" class="level3" data-number="9.4.2">
<h3 data-number="9.4.2" class="anchored" data-anchor-id="example-scheme-2-simple-random-sample"><span class="header-section-number">9.4.2</span> Example Scheme 2: Simple Random Sample?</h3>
<p>Consider the following sampling scheme:</p>
<ul>
<li>A class roster has 1200 students listed alphabetically.</li>
<li>Pick one of the first 10 students on the list at random (e.g.&nbsp;Student 8).</li>
<li>To create your sample, take that student and every 10th student listed after that (e.g.&nbsp;Students 8, 18, 28, 38, etc.).</li>
</ul>
<details>
<summary>
Is this a probability sample?
</summary>
<p>Yes. For a sample [n, n + 10, n + 20, …, n + 1190], where 1 &lt;= n &lt;= 10, the probability of that sample is 1/10. Otherwise, the probability is 0.</p>
Only 10 possible samples!
</details>
<details>
<summary>
Does each student have the same probability of being selected?
</summary>
Yes. Each student is chosen with a probability of 1/10. Since there are only 10 possible samples, each sample is equally likely, and each student is in exactly 1 of the 10 samples, there is exactly 1 out of 10 possible outcomes where any specific student is selected.
</details>
<details>
<summary>
Is this a simple random sample?
</summary>
No.&nbsp;The chance of selecting (8, 18) is 1/10; the chance of selecting (8, 9) is 0.
</details>
</section>
<section id="example-scheme-3-stratified-random-sampling" class="level3" data-number="9.4.3">
<h3 data-number="9.4.3" class="anchored" data-anchor-id="example-scheme-3-stratified-random-sampling"><span class="header-section-number">9.4.3</span> Example Scheme 3: Stratified Random Sampling</h3>
<p>Suppose you want to interview a representative sample of <strong>12 students</strong> enrolled in Data 100.</p>
<ul>
<li>Suppose there are <strong>1,200 students</strong> in Data 100.</li>
<li><strong>100 students</strong> are graduate students. The remaining <strong>1,100</strong> are undergraduates.</li>
<li>I conduct an SRS with <strong>n=1</strong> on the 100 graduate students, and an SRS with <strong>n=11</strong> on the 1,100 undergraduates.</li>
</ul>
<details>
<summary>
Does each student have the same probability of being selected?
</summary>
<p><strong>Yes</strong>. Each student is chosen with probability 1/100</p>
</details>
<details>
<summary>
Is there any benefit or downside to sampling this way?
</summary>
<p><strong>Yes, a benefit!</strong> We have <strong>guaranteed proportional representation</strong> of undergrads and grad students. In other words, we have <strong>reduced chance error</strong> (i.e., variance).</p>
</details>
</section>
</section>
<section id="non-representative-sampling-and-post-stratification" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="non-representative-sampling-and-post-stratification"><span class="header-section-number">9.5</span> Non-representative Sampling and Post-stratification</h2>
<p>Often times, for whatever reason, we cannot obtain a truly representative sample. This often happens in industry.</p>
<ul>
<li>When conducting customer surveys, not everyone responds or provides contact info</li>
<li>When polling for election prediction, not all voters are reachable or want to talk to you</li>
<li>When conducting clinical trials, patients have to voluntarily join a trial, and it is possible that people who volunteer to join a clinical trial differ in some way from the average patient who the treatment is for, and thus they are not representative of the population the trial is meant to study.</li>
</ul>
<section id="example-non-representative-sampling-scheme" class="level3" data-number="9.5.1">
<h3 data-number="9.5.1" class="anchored" data-anchor-id="example-non-representative-sampling-scheme"><span class="header-section-number">9.5.1</span> Example: Non-representative Sampling Scheme</h3>
<ul>
<li>A class has 1200 students enrolled in it, 100 of whom are graduate students, and the other 1100 of whom are undergraduate students.</li>
<li>The professor is trying to understand the proportion of students who are enjoying the class, and they are surveying the 20 students who are in their office hours.</li>
<li>In this room there are 10 grad students, and 10 undergrads.</li>
<li>9 of the grad students are enjoying the class, and 5 of the undergrads are enjoying the class</li>
</ul>

<details>
<summary>
Based on just these 20 students, how can we make a good guess of the percentage of all students in this class who are enjoying it?
</summary>
<p>We might notice that although the amount of grads and undergrads in the room is equal, across the whole class there are a lot more undergrads than grad students. We might then want to <strong>overweight</strong> the opinions of the 10 undergrads relative to the 10 grad students.</p>
<p>However, in order to trust this estimate, we have made a pretty <strong>huge assumption</strong>! This assumes that the 10 grad students are representative of all 100 grad students, and the 10 undergrads are representative of all 1100 undergrads.</p>
<p>(9 / 10) * (100 / 1200) + (5 / 10) * (1100 / 1200) = 53.3%<br>
<br>
This is an example of <strong>post-stratification</strong>. After we took a non-representative sample (the students in professor OH) of the population we’re interested in (all students in this class), we used knowledge about the population to <strong>reweight</strong> responses.</p>
<p></p>
</details></section>
</section>
<section id="demo-the-1936-presidential-election-results" class="level2" data-number="9.6">
<h2 data-number="9.6" class="anchored" data-anchor-id="demo-the-1936-presidential-election-results"><span class="header-section-number">9.6</span> Demo: The 1936 Presidential Election Results</h2>
<p>Let’s start with the real election results from the 1936 election.</p>
<ul>
<li>Each row of <code>votes</code> represents a single voter.</li>
<li><code>voted_dem</code> is 0/1 variable indicating whether the voter voted for Franklin D. Roosevelt, who was the Democratic candidate in 1936. If 0, the voter voted for Alf Landon, the Republican candidate.</li>
</ul>
<p>Votes for other parties are excluded from this dataset.</p>
<div id="2082f677" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> zipfile</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>sns.set_theme(style<span class="op">=</span><span class="st">'darkgrid'</span>, font_scale <span class="op">=</span> <span class="fl">1.5</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>              rc<span class="op">=</span>{<span class="st">'figure.figsize'</span>:(<span class="dv">7</span>,<span class="dv">5</span>)})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="37890eb8" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> zipfile.ZipFile(<span class="st">"data/1936_votes.zip"</span>, <span class="st">'r'</span>) <span class="im">as</span> z:</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> z.<span class="bu">open</span>(<span class="st">"1936_votes.csv"</span>) <span class="im">as</span> csv_file:</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>        votes <span class="op">=</span> pd.read_csv(csv_file)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>votes.head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">voted_dem</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>1</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>1</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>1</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>1</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>How many votes were cast for either Roosevelt or Landon in 1936?</p>
<div id="151ed1af" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="bu">len</span>(votes)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<pre><code>44430549</code></pre>
</div>
</div>
<p>What fraction of voters voted for Roosevelt, the Democratic candidate?</p>
<div id="dbd453f7" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>votes[<span class="st">'voted_dem'</span>].<span class="bu">sum</span>() <span class="op">/</span> <span class="bu">len</span>(votes)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<pre><code>0.6245897614274358</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>But wait, don’t the slides say that Roosevelt won 61% of the vote?</p>
<p>Yes! But, he won 61% of <strong>all</strong> votes. If we filter to just the voters who voted for Roosevelt or Landon, Roosevelt won 62.5% of votes.</p>
</blockquote>
<p>Useful tip: The mean of a 0/1 column is the same as the proportion of values that are 1.</p>
<div id="2e8c731b" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>votes[<span class="st">'voted_dem'</span>].mean()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>0.6245897614274358</code></pre>
</div>
</div>
<p>Of the <strong>44,430,549</strong> voters who voted for either Roosevelt or Landon, <strong>62.5%</strong> voted for Roosevelt.</p>
<section id="simple-random-sample-srs" class="level3" data-number="9.6.1">
<h3 data-number="9.6.1" class="anchored" data-anchor-id="simple-random-sample-srs"><span class="header-section-number">9.6.1</span> 🎩 Simple Random Sample (SRS)</h3>
<p>Note: An SRS is sometimes called a “names in a hat” sample, since it’s a lot like putting each observation on a slip of paper, putting all the slips in a big hat, and then randomly drawing slips one at a time.</p>
<p>If we were to take a simple random sample of just 1,000 voters and calculate the proportion who planned to vote for Roosevelt, how close would we be to 62.5%?</p>
<div id="3b6e0658" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>votes[<span class="st">'voted_dem'</span>].sample(<span class="dv">1000</span>).mean()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>0.632</code></pre>
</div>
</div>
<p>Note that the cell above is a little slow, since we’re sampling from a <code>DataFrame</code> with almost 45 million rows.</p>
<p>We can speed up the sampling using <code>NumPy</code>:</p>
<div id="a7a89e9e" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Construct a random number generator object.</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># No need to be familiar with using NumPy this way in Data 100!</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng()</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>n_votes <span class="op">=</span> <span class="bu">len</span>(votes)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate 1000 random integers from 0 to (number of votes - 1)</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>idx <span class="op">=</span> rng.integers(low<span class="op">=</span><span class="dv">0</span>, high<span class="op">=</span>n_votes<span class="op">-</span><span class="dv">1</span>, size<span class="op">=</span><span class="dv">1000</span>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>votes[<span class="st">'voted_dem'</span>].iloc[idx].mean()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>0.61</code></pre>
</div>
</div>
<p>Both of the estimates above are pretty close to 62.5%! They are much closer than the estimate from the Literary Digest poll, which predicted that 43% of votes would go to Roosevelt.</p>
<p>This is no fluke! If we repeat this over and over, we tend to hover around 62.5%.</p>
<div id="532e2131" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">10</span>):</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  idx <span class="op">=</span> rng.integers(low<span class="op">=</span><span class="dv">0</span>, high<span class="op">=</span>n_votes<span class="op">-</span><span class="dv">1</span>, size<span class="op">=</span><span class="dv">1000</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(votes[<span class="st">'voted_dem'</span>].iloc[idx].mean())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.634
0.606
0.644
0.635
0.635
0.637
0.612
0.612
0.625
0.609</code></pre>
</div>
</div>
<p>Let’s randomly generate 10,000 estimates:</p>
<div id="27699609" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>nrep <span class="op">=</span> <span class="dv">10000</span>   <span class="co"># number of simulations</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">1000</span>       <span class="co"># size of our sample</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> []   <span class="co"># list to store the sampling results</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, nrep):</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    idx <span class="op">=</span> rng.integers(low<span class="op">=</span><span class="dv">0</span>, high<span class="op">=</span>n_votes, size<span class="op">=</span><span class="dv">1000</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    results.append(votes[<span class="st">'voted_dem'</span>].iloc[idx].mean())</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="co"># First 10 simulated sample proportions</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>results[:<span class="dv">10</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>[0.601, 0.638, 0.615, 0.597, 0.609, 0.634, 0.641, 0.629, 0.571, 0.651]</code></pre>
</div>
</div>
<p>Plotting our estimates with KDE:</p>
<div id="a3defadb" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">3</span>))</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>p <span class="op">=</span> sns.histplot(x<span class="op">=</span>results, kde<span class="op">=</span><span class="va">True</span>, bins<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Make x-axis centered at 0.625 with 0.01 intervals</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>p.set_xticks(np.arange(<span class="fl">0.625</span> <span class="op">-</span> <span class="dv">5</span> <span class="op">*</span> <span class="fl">0.01</span>, <span class="fl">0.625</span> <span class="op">+</span> <span class="dv">5</span> <span class="op">*</span> <span class="fl">0.01</span>, <span class="fl">0.01</span>))<span class="op">;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="sampling_files/figure-html/cell-11-output-1.png" width="1002" height="274" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>We get an approximate normal distribution centered around 62.5%, with most of the mass of the distribution (say, 95% of the mass) within about 3 percentage points (0.03) on each side.</p>
<p>As it turns out, with a sample size of 1000, our estimate of the proportion of voters supporting Roosevelt has a margin of error of about 3 percentage points (3pp) at a 95% confidence level (CL), so long as we take a simple random sample (SRS) of actual voters.</p>
<ul>
<li>Note: You tend to see 3pp and 95% CL quite a lot in political polling!</li>
</ul>
<p>We’ll learn what these values mean and how to calculate them when we (re)learn the Central Limit Theorem later in the semester.</p>
</section>
</section>
<section id="demo-revisiting-the-1936-literary-digest-poll" class="level2" data-number="9.7">
<h2 data-number="9.7" class="anchored" data-anchor-id="demo-revisiting-the-1936-literary-digest-poll"><span class="header-section-number">9.7</span> Demo: Revisiting the 1936 Literary Digest Poll</h2>
<p>The <code>poll</code> <code>DataFrame</code> contains a summary of the 1936 Literary Digest Poll, along with polling results and actual election results from 1932 and 1936.</p>
<ul>
<li>Each row of <code>poll</code> represents a U.S. state.</li>
<li><code>state</code>: name of the U.S. state.</li>
<li><code>electoral_votes</code>: # electoral votes allocated to the given state.</li>
<li><code>actual_dem_1936</code>: # votes for Roosevelt (the Democratic candidate) in 1936.</li>
<li><code>actual_rep_1936</code>: # votes for Landon (the Republican candidate) in 1936.</li>
<li><code>ld_dem_1936</code>: # Literary Digest respondents who planned to vote for Roosevelt in 1936.</li>
<li><code>ld_rep_1936</code>: # Literary Digest respondents who plannted to vote for Landon in 1936.</li>
</ul>
<p>Literary Digest also had a 1932 poll! We will use this data for post-stratification: * <code>actual_dem_1932</code>: # votes for the Democratic candidate in 1932. * <code>actual_rep_1932</code>: # votes for the Republican candidate in 1932. * <code>ld_dem_1932</code>: # of 1936 Literary Digest respondents who voted for the Democratic candidate in 1932. * <code>ld_rep_1932</code>: # of 1936 Literary Digest respondents who voted for Republican candidate in 1932.</p>
<p>Note: Votes from parties other than Democratic and Republican are excluded from this dataset.</p>
<div id="60bb31be" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>poll <span class="op">=</span> pd.read_csv(<span class="st">'data/literary-digest-summary-data.csv'</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>poll.head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">state</th>
<th data-quarto-table-cell-role="th">electoral_votes</th>
<th data-quarto-table-cell-role="th">actual_dem_1936</th>
<th data-quarto-table-cell-role="th">actual_rep_1936</th>
<th data-quarto-table-cell-role="th">ld_rep_1936</th>
<th data-quarto-table-cell-role="th">ld_dem_1936</th>
<th data-quarto-table-cell-role="th">actual_dem_1932</th>
<th data-quarto-table-cell-role="th">actual_rep_1932</th>
<th data-quarto-table-cell-role="th">ld_dem_1932</th>
<th data-quarto-table-cell-role="th">ld_rep_1932</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Alabama</td>
<td>11</td>
<td>238196</td>
<td>35358</td>
<td>3060</td>
<td>10082</td>
<td>207910</td>
<td>34675</td>
<td>9828</td>
<td>1589</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Arizona</td>
<td>3</td>
<td>86722</td>
<td>33433</td>
<td>2337</td>
<td>1975</td>
<td>79264</td>
<td>36104</td>
<td>2202</td>
<td>1679</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Arkansas</td>
<td>9</td>
<td>146765</td>
<td>32049</td>
<td>2724</td>
<td>7608</td>
<td>189602</td>
<td>28467</td>
<td>7608</td>
<td>1566</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>California</td>
<td>22</td>
<td>1766836</td>
<td>836431</td>
<td>89516</td>
<td>77245</td>
<td>1324157</td>
<td>847902</td>
<td>69720</td>
<td>80525</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>Colorado</td>
<td>6</td>
<td>295021</td>
<td>181267</td>
<td>15949</td>
<td>10025</td>
<td>250877</td>
<td>189617</td>
<td>9970</td>
<td>13619</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>As a sanity check, let’s make sure we have the same number of votes as the first dataset (44,430,549):</p>
<div id="5bd8c215" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>poll[<span class="st">'actual_dem_1936'</span>].<span class="bu">sum</span>() <span class="op">+</span> poll[<span class="st">'actual_rep_1936'</span>].<span class="bu">sum</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>44430549</code></pre>
</div>
</div>
<p>Let’s also check that we get the reported Literary Digest prediction of 43% for Roosevelt.</p>
<ul>
<li>Remember, Roosevelt received 62.5% of the actual vote.</li>
</ul>
<div id="c148339b" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>poll[<span class="st">'ld_dem_1936'</span>].<span class="bu">sum</span>() <span class="op">/</span> (poll[<span class="st">'ld_dem_1936'</span>].<span class="bu">sum</span>() <span class="op">+</span> poll[<span class="st">'ld_rep_1936'</span>].<span class="bu">sum</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>0.4289439704056572</code></pre>
</div>
</div>
<section id="post-stratification-with-literary-digest-responses-from-1932-and-1936" class="level3" data-number="9.7.1">
<h3 data-number="9.7.1" class="anchored" data-anchor-id="post-stratification-with-literary-digest-responses-from-1932-and-1936"><span class="header-section-number">9.7.1</span> 🥞 Post-stratification with Literary Digest responses from 1932 and 1936</h3>
<p>Using <strong>post-stratification</strong>, let’s see if we can improve the Literary Digest poll result using the <strong>same information available to Literary Digest in 1936</strong>.</p>
<ul>
<li>In other words, without using data from the future!</li>
</ul>
<p>Recall the steps of post-stratification:</p>
<ol type="1">
<li>Divide the sample and population into cells defined by chosen characteristics.</li>
<li>Calculate the overall response in each sample cell.</li>
<li>Aggregate over sample cells, reweighting by the size of the corresponding population cell.</li>
</ol>
<p><strong>Sample</strong>: Responses to the Literary Digest poll from 1932, among 1936 poll respondents</p>
<p><strong>Population</strong>: The actual election outcomes in 1932</p>
<p><strong>Cells</strong>: Every combination of state and political party</p>
<blockquote class="blockquote">
<p>Wait, aren’t we interested in the 1936 Literary Digest poll?</p>
<ul>
<li><p>Yes! But, we can use responses from the older 1932 poll and 1932 election results to get our <strong>sample cell weights</strong>, and then use these weights to turn the 1936 poll results into a prediction of the 1936 election results.</p></li>
<li><p>Note that this approach assumes that over- and under-representation of voters among the poll respondents in state and party is the same in 1932 and 1936!</p></li>
</ul>
</blockquote>
<p>Let’s start with step 1. We divide our population and sample into cells defined by each combination of <strong>state</strong> and <strong>choice of party in 1932</strong>:</p>
<ul>
<li>Cell 1: Alabama + Republican in 1932</li>
<li>Cell 2: Alabama + Democratic in 1932</li>
<li>Cell 3: Arizona + Republican in 1932</li>
<li>Cell 4: Arizona + Democratic in 1932</li>
<li>…</li>
</ul>
<blockquote class="blockquote">
<p>Note: Alaska and Hawaii were not U.S. states until after 1936.</p>
</blockquote>
<p>The population cells are already in <code>polls</code>: <code>actual_dem_1932</code> and <code>actual_rep_1932</code> provide the actual vote counts for each party and state in 1932.</p>
<p>The sample cells are also in <code>polls</code>: <code>ld_dem_1932</code> and <code>ld_rep_1932</code> provide the number of responses to the 1932 Literary Digest poll, among 1936 poll respondents, for each party.</p>
<p>Let’s make the <strong>big</strong> assumption that respondents in <code>ld_dem_1932</code> are representative of all voters in <code>actual_dem_1932</code> for each state, and the same for <code>ld_rep_1932</code> and <code>actual_rep_1932</code>.</p>
<ul>
<li><p>In other words, we claim that response rates and outreach for Democrats and Republicans from each state in 1932 can differ, but ultimately <strong>poll respondents from a particular party+state combination are representative of actual voters for each party+state combination</strong>.</p></li>
<li><p>Then, we can calculate the <strong>reweighting factor</strong>, or how over- or under-represented poll respondents are relative to actual voters.</p></li>
<li><p>All we need to do is divide the actual vote counts by the corresponding number of respondents, for each combination of party and state.</p></li>
</ul>
<div id="77a3c597" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>poll[<span class="st">'dem_reweight_factor'</span>] <span class="op">=</span> poll[<span class="st">'actual_dem_1932'</span>] <span class="op">/</span> poll[<span class="st">'ld_dem_1932'</span>]</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>poll[<span class="st">'rep_reweight_factor'</span>] <span class="op">=</span> poll[<span class="st">'actual_rep_1932'</span>] <span class="op">/</span> poll[<span class="st">'ld_rep_1932'</span>]</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>poll.tail()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">state</th>
<th data-quarto-table-cell-role="th">electoral_votes</th>
<th data-quarto-table-cell-role="th">actual_dem_1936</th>
<th data-quarto-table-cell-role="th">actual_rep_1936</th>
<th data-quarto-table-cell-role="th">ld_rep_1936</th>
<th data-quarto-table-cell-role="th">ld_dem_1936</th>
<th data-quarto-table-cell-role="th">actual_dem_1932</th>
<th data-quarto-table-cell-role="th">actual_rep_1932</th>
<th data-quarto-table-cell-role="th">ld_dem_1932</th>
<th data-quarto-table-cell-role="th">ld_rep_1932</th>
<th data-quarto-table-cell-role="th">dem_reweight_factor</th>
<th data-quarto-table-cell-role="th">rep_reweight_factor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">43</th>
<td>Virginia</td>
<td>11</td>
<td>234980</td>
<td>98336</td>
<td>10223</td>
<td>16783</td>
<td>203979</td>
<td>89637</td>
<td>16194</td>
<td>6817</td>
<td>12.595961</td>
<td>13.149039</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">44</th>
<td>Washington</td>
<td>8</td>
<td>459579</td>
<td>206892</td>
<td>21370</td>
<td>15300</td>
<td>353260</td>
<td>208645</td>
<td>16223</td>
<td>17122</td>
<td>21.775257</td>
<td>12.185784</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">45</th>
<td>West Virginia</td>
<td>8</td>
<td>502582</td>
<td>325358</td>
<td>13660</td>
<td>10235</td>
<td>405124</td>
<td>330731</td>
<td>10818</td>
<td>11338</td>
<td>37.449066</td>
<td>29.170136</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">46</th>
<td>Wisconsin</td>
<td>12</td>
<td>802984</td>
<td>380828</td>
<td>33796</td>
<td>20781</td>
<td>707410</td>
<td>347741</td>
<td>24073</td>
<td>25731</td>
<td>29.386034</td>
<td>13.514477</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">47</th>
<td>Wyoming</td>
<td>3</td>
<td>62624</td>
<td>38739</td>
<td>2526</td>
<td>1533</td>
<td>54370</td>
<td>39583</td>
<td>1654</td>
<td>2072</td>
<td>32.871826</td>
<td>19.103764</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Note that <code>dem_reweight_factor</code> is about 36 for Arizona.</p>
<ul>
<li>In other words, there were 36 times as many Democratic voters in Arizona than Democratic poll respondents.</li>
</ul>
<p>Similarly, <code>rep_reweight_factor</code> is about 21.5 for Arizona.</p>
<ul>
<li><p>So, Democratic voters are <strong>underrepresented</strong> in the 1932 Literary Digest poll responses, relative to Republican voters.</p></li>
<li><p>Based on the Republican bias in the Literary Digest sample discussed in lecture (i.e., wealthier folks with phones, cars, and magazines), this is expected!</p></li>
</ul>
<p>Next, we apply these same weights to inflate the 1936 poll results into vote predictions.</p>
<ul>
<li>Again, note that this approach assumes over- and under-representation patterns are the same in the 1932 and 1936 polls!</li>
</ul>
<div id="7d86525d" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>poll[<span class="st">'pred_dem_1936'</span>] <span class="op">=</span> <span class="bu">round</span>(poll[<span class="st">'ld_dem_1936'</span>] <span class="op">*</span> poll[<span class="st">'dem_reweight_factor'</span>])</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>poll[<span class="st">'pred_rep_1936'</span>] <span class="op">=</span> <span class="bu">round</span>(poll[<span class="st">'ld_rep_1936'</span>] <span class="op">*</span> poll[<span class="st">'rep_reweight_factor'</span>])</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>poll.head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">state</th>
<th data-quarto-table-cell-role="th">electoral_votes</th>
<th data-quarto-table-cell-role="th">actual_dem_1936</th>
<th data-quarto-table-cell-role="th">actual_rep_1936</th>
<th data-quarto-table-cell-role="th">ld_rep_1936</th>
<th data-quarto-table-cell-role="th">ld_dem_1936</th>
<th data-quarto-table-cell-role="th">actual_dem_1932</th>
<th data-quarto-table-cell-role="th">actual_rep_1932</th>
<th data-quarto-table-cell-role="th">ld_dem_1932</th>
<th data-quarto-table-cell-role="th">ld_rep_1932</th>
<th data-quarto-table-cell-role="th">dem_reweight_factor</th>
<th data-quarto-table-cell-role="th">rep_reweight_factor</th>
<th data-quarto-table-cell-role="th">pred_dem_1936</th>
<th data-quarto-table-cell-role="th">pred_rep_1936</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Alabama</td>
<td>11</td>
<td>238196</td>
<td>35358</td>
<td>3060</td>
<td>10082</td>
<td>207910</td>
<td>34675</td>
<td>9828</td>
<td>1589</td>
<td>21.154864</td>
<td>21.821901</td>
<td>213283.0</td>
<td>66775.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Arizona</td>
<td>3</td>
<td>86722</td>
<td>33433</td>
<td>2337</td>
<td>1975</td>
<td>79264</td>
<td>36104</td>
<td>2202</td>
<td>1679</td>
<td>35.996367</td>
<td>21.503276</td>
<td>71093.0</td>
<td>50253.0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Arkansas</td>
<td>9</td>
<td>146765</td>
<td>32049</td>
<td>2724</td>
<td>7608</td>
<td>189602</td>
<td>28467</td>
<td>7608</td>
<td>1566</td>
<td>24.921399</td>
<td>18.178161</td>
<td>189602.0</td>
<td>49517.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>California</td>
<td>22</td>
<td>1766836</td>
<td>836431</td>
<td>89516</td>
<td>77245</td>
<td>1324157</td>
<td>847902</td>
<td>69720</td>
<td>80525</td>
<td>18.992499</td>
<td>10.529674</td>
<td>1467076.0</td>
<td>942574.0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>Colorado</td>
<td>6</td>
<td>295021</td>
<td>181267</td>
<td>15949</td>
<td>10025</td>
<td>250877</td>
<td>189617</td>
<td>9970</td>
<td>13619</td>
<td>25.163190</td>
<td>13.922975</td>
<td>252261.0</td>
<td>222058.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Finally, let’s calculate the proportion of <strong>predicted</strong> votes that are allocated to Roosevelt in 1936.</p>
<ul>
<li>Remember that Roosevelt received 62.5% of the <strong>actual</strong> vote in 1936.</li>
</ul>
<div id="16c69329" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>poll[<span class="st">'pred_dem_1936'</span>].<span class="bu">sum</span>() <span class="op">/</span> (poll[<span class="st">'pred_dem_1936'</span>].<span class="bu">sum</span>() <span class="op">+</span> poll[<span class="st">'pred_rep_1936'</span>].<span class="bu">sum</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="16">
<pre><code>0.5422251022375592</code></pre>
</div>
</div>
<p>54% is a majority! Using post-stratification, we have shifted the Literary Digest prediction of a Roosevelt loss with 43% of the vote to a (correct) Roosevelt win with 54%.</p>
<ul>
<li><p>There is no cheating here; we used the same data available to Literary Digest in 1936.</p></li>
<li><p>Note that post-stratification is not perfect. We are still off by almost 10 percentage points. But, we’ve moved in the right direction.</p></li>
</ul>
</section>
</section>
<section id="bonus-follow-up-improvements" class="level2" data-number="9.8">
<h2 data-number="9.8" class="anchored" data-anchor-id="bonus-follow-up-improvements"><span class="header-section-number">9.8</span> 🎁 Bonus: Follow Up Improvements</h2>
<p>As a follow-up exercise, we can compare the predicted 1936 vote totals to the actual 1932 vote totals.</p>
<ul>
<li><p>Then, we could apply a <strong>correction factor</strong> to change the predicted number of 1936 votes to be in line with the total number of votes in 1932.</p></li>
<li><p>This exercise assumes that the total number of votes cast in 1932 would be the same in 1936, but the poll response rates and outreach might change between 1932 and 1936.</p></li>
</ul>
<div id="5c18d7ae" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>poll[<span class="st">'pred_total_1936'</span>] <span class="op">=</span> poll[<span class="st">'pred_dem_1936'</span>] <span class="op">+</span> poll[<span class="st">'pred_rep_1936'</span>]</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>poll[<span class="st">'actual_total_1932'</span>] <span class="op">=</span> poll[<span class="st">'actual_dem_1932'</span>] <span class="op">+</span> poll[<span class="st">'actual_rep_1932'</span>]</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>poll[<span class="st">'correction_factor'</span>] <span class="op">=</span> poll[<span class="st">'actual_total_1932'</span>] <span class="op">/</span> poll[<span class="st">'pred_total_1936'</span>]</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>poll.head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="17">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">state</th>
<th data-quarto-table-cell-role="th">electoral_votes</th>
<th data-quarto-table-cell-role="th">actual_dem_1936</th>
<th data-quarto-table-cell-role="th">actual_rep_1936</th>
<th data-quarto-table-cell-role="th">ld_rep_1936</th>
<th data-quarto-table-cell-role="th">ld_dem_1936</th>
<th data-quarto-table-cell-role="th">actual_dem_1932</th>
<th data-quarto-table-cell-role="th">actual_rep_1932</th>
<th data-quarto-table-cell-role="th">ld_dem_1932</th>
<th data-quarto-table-cell-role="th">ld_rep_1932</th>
<th data-quarto-table-cell-role="th">dem_reweight_factor</th>
<th data-quarto-table-cell-role="th">rep_reweight_factor</th>
<th data-quarto-table-cell-role="th">pred_dem_1936</th>
<th data-quarto-table-cell-role="th">pred_rep_1936</th>
<th data-quarto-table-cell-role="th">pred_total_1936</th>
<th data-quarto-table-cell-role="th">actual_total_1932</th>
<th data-quarto-table-cell-role="th">correction_factor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Alabama</td>
<td>11</td>
<td>238196</td>
<td>35358</td>
<td>3060</td>
<td>10082</td>
<td>207910</td>
<td>34675</td>
<td>9828</td>
<td>1589</td>
<td>21.154864</td>
<td>21.821901</td>
<td>213283.0</td>
<td>66775.0</td>
<td>280058.0</td>
<td>242585</td>
<td>0.866196</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Arizona</td>
<td>3</td>
<td>86722</td>
<td>33433</td>
<td>2337</td>
<td>1975</td>
<td>79264</td>
<td>36104</td>
<td>2202</td>
<td>1679</td>
<td>35.996367</td>
<td>21.503276</td>
<td>71093.0</td>
<td>50253.0</td>
<td>121346.0</td>
<td>115368</td>
<td>0.950736</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Arkansas</td>
<td>9</td>
<td>146765</td>
<td>32049</td>
<td>2724</td>
<td>7608</td>
<td>189602</td>
<td>28467</td>
<td>7608</td>
<td>1566</td>
<td>24.921399</td>
<td>18.178161</td>
<td>189602.0</td>
<td>49517.0</td>
<td>239119.0</td>
<td>218069</td>
<td>0.911969</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>California</td>
<td>22</td>
<td>1766836</td>
<td>836431</td>
<td>89516</td>
<td>77245</td>
<td>1324157</td>
<td>847902</td>
<td>69720</td>
<td>80525</td>
<td>18.992499</td>
<td>10.529674</td>
<td>1467076.0</td>
<td>942574.0</td>
<td>2409650.0</td>
<td>2172059</td>
<td>0.901400</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>Colorado</td>
<td>6</td>
<td>295021</td>
<td>181267</td>
<td>15949</td>
<td>10025</td>
<td>250877</td>
<td>189617</td>
<td>9970</td>
<td>13619</td>
<td>25.163190</td>
<td>13.922975</td>
<td>252261.0</td>
<td>222058.0</td>
<td>474319.0</td>
<td>440494</td>
<td>0.928687</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="db00394e" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>poll[<span class="st">'pred_dem_1936_corrected'</span>] <span class="op">=</span> poll[<span class="st">'pred_dem_1936'</span>] <span class="op">*</span> poll[<span class="st">'correction_factor'</span>]</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>poll[<span class="st">'pred_rep_1936_corrected'</span>] <span class="op">=</span> poll[<span class="st">'pred_rep_1936'</span>] <span class="op">*</span> poll[<span class="st">'correction_factor'</span>]</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>poll[<span class="st">'pred_dem_1936_corrected'</span>].<span class="bu">sum</span>() <span class="op">/</span> (poll[<span class="st">'pred_dem_1936_corrected'</span>].<span class="bu">sum</span>() <span class="op">+</span> poll[<span class="st">'pred_rep_1936_corrected'</span>].<span class="bu">sum</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="18">
<pre><code>0.5419440974611633</code></pre>
</div>
</div>
<p>Looks like a pretty similar prediction for Roosevelt of 54%.</p>
<p>As it turns out, it looks like our original (i.e., uncorrected) predictions had a vote total closer to the true 1936 vote total:</p>
<div id="d66d7102" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Actual 1936 vote total:'</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(poll[<span class="st">'actual_dem_1936'</span>].<span class="bu">sum</span>() <span class="op">+</span> poll[<span class="st">'actual_rep_1936'</span>].<span class="bu">sum</span>())</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Predicted 1936 vote total, uncorrected:'</span>)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(poll[<span class="st">'pred_dem_1936'</span>].<span class="bu">sum</span>() <span class="op">+</span> poll[<span class="st">'pred_rep_1936'</span>].<span class="bu">sum</span>())</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Predicted 1936 vote total, corrected:'</span>)</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(poll[<span class="st">'pred_dem_1936_corrected'</span>].<span class="bu">sum</span>() <span class="op">+</span> poll[<span class="st">'pred_rep_1936_corrected'</span>].<span class="bu">sum</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Actual 1936 vote total:
44430549
Predicted 1936 vote total, uncorrected:
42058418.0
Predicted 1936 vote total, corrected:
38582531.0</code></pre>
</div>
</div>
<p>Furthermore, we can check whether post-stratification would have led to a predicted win for Roosevelt in the electoral college, which is what actually determines the election outcome.</p>
<ul>
<li>To do this, we allocate <strong>all</strong> of the electoral votes in each state to the candidate with the most predicted votes in that state, and then sum up the total number of electoral votes allocated to each candidate across states.</li>
</ul>
<div id="57a1a019" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>poll[<span class="st">'dem_wins'</span>] <span class="op">=</span> poll[<span class="st">'pred_dem_1936'</span>] <span class="op">&gt;</span> poll[<span class="st">'pred_rep_1936'</span>]</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Total predicted Roosevelt electoral votes:'</span>)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(( poll[<span class="st">'dem_wins'</span>] <span class="op">*</span> poll[<span class="st">'electoral_votes'</span>] ).<span class="bu">sum</span>())</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Total predicted Landon electoral votes:'</span>)</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(( (<span class="dv">1</span><span class="op">-</span>poll[<span class="st">'dem_wins'</span>]) <span class="op">*</span> poll[<span class="st">'electoral_votes'</span>] ).<span class="bu">sum</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Total predicted Roosevelt electoral votes:
380
Total predicted Landon electoral votes:
151</code></pre>
</div>
</div>
<p>We (correctly) predict a Roosevelt landslide in the electoral college!</p>
<ul>
<li><p>But, note that the actual electoral college landslide was much bigger: 523 to 8</p></li>
<li><p>This is the largest electoral college landslide since 1820 (as of 2025).</p></li>
</ul>
</section>
<section id="summary" class="level2" data-number="9.9">
<h2 data-number="9.9" class="anchored" data-anchor-id="summary"><span class="header-section-number">9.9</span> Summary</h2>
<p>Understanding the sampling process is what lets us go from describing the data to understanding the world. Without knowing / assuming something about how the data were collected, there is no connection between the sample and the population. Ultimately, the dataset doesn’t tell us about the world behind the data.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../visualization_2/visualization_2.html" class="pagination-link" aria-label="Visualization II">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Visualization II</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../modeling_slr/modeling_slr.html" class="pagination-link" aria-label="Modeling &amp; SLR">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Modeling &amp; SLR</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>