<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Sampling</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="sampling_files/libs/clipboard/clipboard.min.js"></script>
<script src="sampling_files/libs/quarto-html/quarto.js"></script>
<script src="sampling_files/libs/quarto-html/popper.min.js"></script>
<script src="sampling_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="sampling_files/libs/quarto-html/anchor.min.js"></script>
<link href="sampling_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="sampling_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="sampling_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="sampling_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="sampling_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#censuses-and-surveys" id="toc-censuses-and-surveys" class="nav-link active" data-scroll-target="#censuses-and-surveys">Censuses and Surveys</a></li>
  <li><a href="#bias-a-case-study" id="toc-bias-a-case-study" class="nav-link" data-scroll-target="#bias-a-case-study">Bias: A Case Study</a></li>
  <li><a href="#probability-samples" id="toc-probability-samples" class="nav-link" data-scroll-target="#probability-samples">Probability Samples</a>
  <ul>
  <li><a href="#example-scheme-1-probability-sample" id="toc-example-scheme-1-probability-sample" class="nav-link" data-scroll-target="#example-scheme-1-probability-sample">Example Scheme 1: Probability Sample</a></li>
  <li><a href="#example-scheme-2-simple-random-sample" id="toc-example-scheme-2-simple-random-sample" class="nav-link" data-scroll-target="#example-scheme-2-simple-random-sample">Example Scheme 2: Simple Random Sample</a></li>
  <li><a href="#demo-barbie-v.-oppenheimer" id="toc-demo-barbie-v.-oppenheimer" class="nav-link" data-scroll-target="#demo-barbie-v.-oppenheimer">Demo: Barbie v. Oppenheimer</a>
  <ul>
  <li><a href="#convenience-sample-retirees" id="toc-convenience-sample-retirees" class="nav-link" data-scroll-target="#convenience-sample-retirees">Convenience Sample: Retirees</a></li>
  <li><a href="#check-for-bias" id="toc-check-for-bias" class="nav-link" data-scroll-target="#check-for-bias">Check for Bias</a></li>
  <li><a href="#simple-random-sample" id="toc-simple-random-sample" class="nav-link" data-scroll-target="#simple-random-sample">Simple Random Sample</a></li>
  <li><a href="#quantifying-chance-error" id="toc-quantifying-chance-error" class="nav-link" data-scroll-target="#quantifying-chance-error">Quantifying Chance Error</a></li>
  </ul></li>
  <li><a href="#multinomial-probabilities" id="toc-multinomial-probabilities" class="nav-link" data-scroll-target="#multinomial-probabilities">Multinomial Probabilities</a>
  <ul>
  <li><a href="#example-marbles" id="toc-example-marbles" class="nav-link" data-scroll-target="#example-marbles">Example: Marbles</a></li>
  <li><a href="#multinomial-probabilities-generalized" id="toc-multinomial-probabilities-generalized" class="nav-link" data-scroll-target="#multinomial-probabilities-generalized">Multinomial Probabilities: Generalized</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#comparing-convenience-sample-and-srs" id="toc-comparing-convenience-sample-and-srs" class="nav-link" data-scroll-target="#comparing-convenience-sample-and-srs">Comparing Convenience Sample and SRS</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Sampling</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Learning Outcomes
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<ul>
<li>Understand how to appropriately collect data to help answer a question.</li>
</ul>
</div>
</div>
</div>
<p>In data science, understanding characteristics of a population starts with having quality data to investigate. While it is often impossible to collect all the data describing a population, we can overcome this by properly sampling from the population. In this note, we will discuss appropriate techniques for sampling from populations.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/data_life_cycle_sampling.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Lifecycle diagram</figcaption>
</figure>
</div>
<section id="censuses-and-surveys" class="level2">
<h2 class="anchored" data-anchor-id="censuses-and-surveys">Censuses and Surveys</h2>
<p>In general: a <strong>census</strong> is “an official count or survey of a <strong>population</strong>, typically recording various details of <strong>individuals</strong>.” An example is the U.S. Decennial Census which was held in April 2020. It counts <em>every person</em> living in all 50 states, DC, and US territories, not just citizens. Participation is required by law (it is mandated by the U.S. Constitution). Important uses include the allocation of Federal funds, congressional representation, and drawing congressional and state legislative districts. The census is composed of a <strong>survey</strong> mailed to different housing addresses in the United States.</p>
<p>A <strong>survey</strong> is a set of questions. An example is workers sampling individuals and households. What is asked and how it is asked can affect how the respondent answers or even whether or not they answer in the first place.</p>
<p>While censuses are great, it is often very difficult and expensive to survey everyone in a population. Imagine the amount of resources, money, time, and energy the U.S. spent on the 2020 Census. While this does give us more accurate information about the population, it’s often infeasible to execute. Thus, we usually survey a subset of the population instead.</p>
<p>A <strong>sample</strong> is (usually) a subset of the population that is often used to make inferences about the population. If our sample is a good representation of our population, then we can use it to glean useful information at a lower cost. That being said, how the sample is drawn will affect the reliability of such inferences. Two common sources of error in sampling are <strong>chance error</strong>, where random samples can vary from what is expected in any direction, and <strong>bias</strong>, which is a systematic error in one direction. Biases can be the result of many things, for example, our sampling scheme or survey methods.</p>
<p>Let’s define some useful vocabulary:</p>
<ul>
<li><strong>Population</strong>: The group that you want to learn something about.
<ul>
<li><strong>Individuals</strong> in a population are not always people. Other populations include bacteria in your gut (sampled using DNA sequencing), trees of a certain species, small businesses receiving a microloan, or published results in an academic journal or field.</li>
</ul></li>
<li><strong>Sampling Frame</strong>: The list from which the sample is drawn.
<ul>
<li>For example, if sampling people, then the sampling frame is the set of all people that could possibly end up in your sample.</li>
</ul></li>
<li><strong>Sample</strong>: Who you actually end up sampling. The sample is therefore a subset of your <em>sampling frame</em>.</li>
</ul>
<p>While ideally, these three sets would be exactly the same, they usually aren’t in practice. For example, there may be individuals in your sampling frame (and hence, your sample) that are not in your population. And generally, sample sizes are much smaller than population sizes.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/samplingframe.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Sampling_Frames</figcaption>
</figure>
</div>
</section>
<section id="bias-a-case-study" class="level2">
<h2 class="anchored" data-anchor-id="bias-a-case-study">Bias: A Case Study</h2>
<p>The following case study is adapted from <em>Statistics</em> by Freedman, Pisani, and Purves, W.W. Norton NY, 1978.</p>
<p>In 1936, President Franklin D. Roosevelt (Democratic) went up for re-election against Alf Landon (Republican). As is usual, <strong>polls</strong> were conducted in the months leading up to the election to try and predict the outcome. The <em>Literary Digest</em> was a magazine that had successfully predicted the outcome of 5 general elections coming into 1936. In their polling for the 1936 election, they sent out their survey to 10 million individuals whom they found from phone books, lists of magazine subscribers, and lists of country club members. Of the roughly 2.4 million people who filled out the survey, only 43% reported they would vote for Roosevelt; thus, the <em>Digest</em> predicted that Landon would win.</p>
<p>On election day, Roosevelt won in a landslide, winning 61% of the popular vote of about 45 million voters. How could the <em>Digest</em> have been so wrong with their polling?</p>
<p>It turns out that the <em>Literary Digest</em> sample was not representative of the population. Their sampling frame of people found in phone books, lists of magazine subscribers, and lists of country club members were more affluent and tended to vote Republican. As such, their sampling frame was inherently skewed in Landon’s favor. The <em>Literary Digest</em> completely overlooked the lion’s share of voters who were still suffering through the Great Depression. Furthermore, they had a dismal response rate (about 24%); who knows how the other non-respondents would have polled? The <em>Digest</em> folded just 18 months after this disaster.</p>
<p>At the same time, George Gallup, a rising statistician, also made predictions about the 1936 elections. Despite having a smaller sample size of “only” 50,000 (this is still more than necessary; more when we cover the Central Limit Theorem), his estimate that 56% of voters would choose Roosevelt was much closer to the actual result (61%). Gallup also predicted the <em>Digest</em>’s prediction within 1% with a sample size of only 3000 people by anticipating the <em>Digest</em>’s affluent sampling frame and subsampling those individuals.</p>
<p>So what’s the moral of the story? Samples, while convenient, are subject to chance error and <strong>bias</strong>. Election polling, in particular, can involve many sources of bias. To name a few:</p>
<ul>
<li><strong>Selection bias</strong> systematically excludes (or favors) particular groups.
<ul>
<li>Example: the Literary Digest poll excludes people not in phone books.</li>
<li>How to avoid: Examine the sampling frame and the method of sampling.</li>
</ul></li>
<li><strong>Response bias</strong> occurs because people don’t always respond truthfully. Survey designers pay special detail to the nature and wording of questions to avoid this type of bias.
<ul>
<li>Example: Illegal immigrants might not answer truthfully when asked citizenship questions on the census survey.</li>
<li>How to avoid: Examine the nature of questions and the method of surveying.</li>
</ul></li>
<li><strong>Non-response bias</strong> occurs because people don’t always respond to survey requests, which can skew responses.
<ul>
<li>Example: Only 2.4m out of 10m people responded to the <em>Literary Digest</em>’s poll.</li>
<li>How to avoid: Keep surveys short, and be persistent.</li>
</ul></li>
</ul>
<p>Today, the <em>Gallup Poll</em> is one of the leading polls for election results. The many sources of biases – who responds to polls? Do voters tell the truth? How can we predict turnout? – still remain, but the <em>Gallup Poll</em> uses several tactics to mitigate them. Within their sampling frame of “civilian, non-institutionalized population” of adults in telephone households in continental U.S., they use random digit dialing to include both listed/unlisted phone numbers and to avoid selection bias. Additionally, they use a within-household selection process to randomly select households with one or more adults. If no one answers, re-call multiple times to avoid non-response bias.</p>
</section>
<section id="probability-samples" class="level2">
<h2 class="anchored" data-anchor-id="probability-samples">Probability Samples</h2>
<p>When sampling, it is essential to focus on the quality of the sample rather than the quantity of the sample. A huge sample size does not fix a bad sampling method. Our main goal is to gather a sample that is representative of the population it came from. In this section, we’ll explore the different types of sampling and their pros and cons.</p>
<p>A <strong>convenience sample</strong> is whatever you can get ahold of; this type of sampling is <em>non-random</em>. Note that haphazard sampling is not necessarily random sampling; there are many potential sources of bias.</p>
<p>In a <strong>probability sample</strong>, we provide the <strong>chance</strong> that any specified <strong>set</strong> of individuals will be in the sample (individuals in the population can have different chances of being selected; they don’t all have to be uniform), and we sample at random based off this known chance. For this reason, probability samples are also called <strong>random samples</strong>. The randomness provides a few benefits:</p>
<ul>
<li>Because we know the source probabilities, we can <strong>measure the errors</strong>.</li>
<li>Sampling at random gives us a more representative sample of the population, which <strong>reduces bias</strong>. (Note: this is only the case when the probability distribution we’re sampling from is accurate. Random samples using “bad” or inaccurate distributions can produce biased estimates of population quantities.)</li>
<li>Probability samples allow us to <strong>estimate</strong> the <strong>bias</strong> and <strong>chance error</strong>, which helps us <strong>quantify uncertainty</strong> (more in a future lecture).</li>
</ul>
<p>The real world is usually more complicated, and we often don’t know the initial probabilities. For example, we do not generally know the probability that a given bacterium is in a microbiome sample or whether people will answer when Gallup calls landlines. That being said, still we try to model probability sampling to the best of our ability even when the sampling or measurement process is not fully under our control.</p>
<p>A few common random sampling schemes:</p>
<ul>
<li>A <strong>random sample with replacement</strong> is a sample drawn <strong>uniformly</strong> at random <strong>with</strong> replacement.
<ul>
<li>Random doesn’t always mean “uniformly at random,” but in this specific context, it does.</li>
<li>Some individuals in the population might get picked more than once.</li>
</ul></li>
<li>A <strong>simple random sample (SRS)</strong> is a sample drawn <strong>uniformly</strong> at random <strong>without</strong> replacement.
<ul>
<li>Every individual (and subset of individuals) has the same chance of being selected.</li>
<li>Every pair has the same chance as every other pair.</li>
<li>Every triple has the same chance as every other triple.</li>
<li>And so on.</li>
</ul></li>
<li>A <strong>stratified random sample</strong>, where random sampling is performed on strata (specific groups), and the groups together compose a sample.</li>
</ul>
<section id="example-scheme-1-probability-sample" class="level3">
<h3 class="anchored" data-anchor-id="example-scheme-1-probability-sample">Example Scheme 1: Probability Sample</h3>
<p>Suppose we have 3 TA’s (<strong>A</strong>lan, <strong>B</strong>ennett, <strong>C</strong>eline): I decide to sample 2 of them as follows:</p>
<ul>
<li>I choose A with probability 1.0</li>
<li>I choose either B or C, each with a probability of 0.5.</li>
</ul>
<p>We can list all the possible outcomes and their respective probabilities in a table:</p>
<table class="table">
<thead>
<tr class="header">
<th>Outcome</th>
<th>Probability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>{A, B}</td>
<td>0.5</td>
</tr>
<tr class="even">
<td>{A, C}</td>
<td>0.5</td>
</tr>
<tr class="odd">
<td>{B, C}</td>
<td>0</td>
</tr>
</tbody>
</table>
<p>This is a <strong>probability sample</strong> (though not a great one). Of the 3 people in my population, I know the chance of getting each subset. Suppose I’m measuring the average distance TAs live from campus.</p>
<ul>
<li>This scheme does not see the entire population!</li>
<li>My estimate using the single sample I take has some chance error depending on if I see AB or AC.</li>
<li>This scheme is biased towards A’s response.</li>
</ul>
</section>
<section id="example-scheme-2-simple-random-sample" class="level3">
<h3 class="anchored" data-anchor-id="example-scheme-2-simple-random-sample">Example Scheme 2: Simple Random Sample</h3>
<p>Consider the following sampling scheme:</p>
<ul>
<li>A class roster has 1100 students listed alphabetically.</li>
<li>Pick one of the first 10 students on the list at random (e.g.&nbsp;Student 8).</li>
<li>To create your sample, take that student and every 10th student listed after that (e.g.&nbsp;Students 8, 18, 28, 38, etc.).</li>
</ul>
<details>
<summary>
<ol type="1">
<li>Is this a probability sample?
</li></ol></summary>

<p>Yes. For a sample [n, n + 10, n + 20, …, n + 1090], where 1 &lt;= n &lt;= 10, the probability of that sample is 1/10. Otherwise, the probability is 0.</p>
Only 10 possible samples!
</details>
<details>
<summary>
<ol start="2" type="1">
<li>Does each student have the same probability of being selected?
</li></ol></summary>

Yes. Each student is chosen with a probability of 1/10.
</details>
<details>
<summary>
<ol start="3" type="1">
<li>Is this a simple random sample?
</li></ol></summary>

No.&nbsp;The chance of selecting (8, 18) is 1/10; the chance of selecting (8, 9) is 0.
</details>
</section>
<section id="demo-barbie-v.-oppenheimer" class="level3">
<h3 class="anchored" data-anchor-id="demo-barbie-v.-oppenheimer">Demo: Barbie v. Oppenheimer</h3>
<p>We are trying to collect a sample from Berkeley residents to predict the which one of Barbie and Oppenheimer would perform better on their opening day, July 21st.</p>
<p>First, let’s grab a dataset that has every single resident in Berkeley (this is a fake dataset) and which movie they <strong>actually</strong> watched on July 21st.</p>
<p>Let’s load in the <code>movie.csv</code> table. We can assume that:</p>
<ul>
<li><code>is_male</code> is a boolean that indicates if a resident identifies as male.</li>
<li>There are only two movies they can watch on July 21st: Barbie and Oppenheimer.</li>
<li>Every resident watches a movie (either Barbie or Oppenheimer) on July 21st.</li>
</ul>
<div class="cell" data-execution_count="1">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>sns.set_theme(style<span class="op">=</span><span class="st">'darkgrid'</span>, font_scale <span class="op">=</span> <span class="fl">1.5</span>,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>              rc<span class="op">=</span>{<span class="st">'figure.figsize'</span>:(<span class="dv">7</span>,<span class="dv">5</span>)})</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>movie <span class="op">=</span> pd.read_csv(<span class="st">"data/movie.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># create a 1/0 int that indicates Barbie vote</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>movie[<span class="st">'barbie'</span>] <span class="op">=</span> (movie[<span class="st">'movie'</span>] <span class="op">==</span> <span class="st">'Barbie'</span>).astype(<span class="bu">int</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>movie.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">age</th>
<th data-quarto-table-cell-role="th">is_male</th>
<th data-quarto-table-cell-role="th">movie</th>
<th data-quarto-table-cell-role="th">barbie</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>35</td>
<td>False</td>
<td>Barbie</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>42</td>
<td>True</td>
<td>Oppenheimer</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>55</td>
<td>False</td>
<td>Barbie</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>77</td>
<td>True</td>
<td>Oppenheimer</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>31</td>
<td>False</td>
<td>Barbie</td>
<td>1</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>What fraction of Berkeley residents chose Barbie?</p>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>actual_barbie <span class="op">=</span> np.mean(movie[<span class="st">"barbie"</span>])</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>actual_barbie</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>0.5302792307692308</code></pre>
</div>
</div>
<p>This is the <strong>actual outcome</strong> of the competition. Based on this result, Barbie would win. How did our sample of retirees do?</p>
<section id="convenience-sample-retirees" class="level4">
<h4 class="anchored" data-anchor-id="convenience-sample-retirees">Convenience Sample: Retirees</h4>
<p>Let’s take a convenience sample of people who have retired (&gt;= 65 years old). What proportion of them went to see Barbie instead of Oppenheimer?</p>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>convenience_sample <span class="op">=</span> movie[movie[<span class="st">'age'</span>] <span class="op">&gt;=</span> <span class="dv">65</span>] <span class="co"># take a convenience sample of retirees</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>np.mean(convenience_sample[<span class="st">"barbie"</span>]) <span class="co"># what proportion of them saw Barbie? </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>0.3744755089093924</code></pre>
</div>
</div>
<p>Based on this result, we would have predicted that Oppenheimer would win! What happened? Is it possible that our sample is too small or noisy?</p>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># what's the size of our sample? </span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="bu">len</span>(convenience_sample)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>359396</code></pre>
</div>
</div>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># what proportion of our data is in the convenience sample? </span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="bu">len</span>(convenience_sample)<span class="op">/</span><span class="bu">len</span>(movie)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>0.27645846153846154</code></pre>
</div>
</div>
<p>Seems like our sample is rather large (roughly 360,000 people), so the error is likely not due to solely to chance.</p>
</section>
<section id="check-for-bias" class="level4">
<h4 class="anchored" data-anchor-id="check-for-bias">Check for Bias</h4>
<p>Let us aggregate all choices by age and visualize the fraction of Barbie views, split by gender.</p>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>votes_by_barbie <span class="op">=</span> movie.groupby([<span class="st">"age"</span>,<span class="st">"is_male"</span>]).agg(<span class="st">"mean"</span>, numeric_only<span class="op">=</span><span class="va">True</span>).reset_index()</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>votes_by_barbie.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">age</th>
<th data-quarto-table-cell-role="th">is_male</th>
<th data-quarto-table-cell-role="th">barbie</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>18</td>
<td>False</td>
<td>0.819594</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>18</td>
<td>True</td>
<td>0.667001</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>19</td>
<td>False</td>
<td>0.812214</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>19</td>
<td>True</td>
<td>0.661252</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>20</td>
<td>False</td>
<td>0.805281</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-execution_count="12">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A common matplotlib/seaborn pattern: create the figure and axes object, pass ax</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># to seaborn for drawing into, and later fine-tune the figure via ax.</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()<span class="op">;</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>red_blue <span class="op">=</span> [<span class="st">"#bf1518"</span>, <span class="st">"#397eb7"</span>]</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> sns.color_palette(red_blue):</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    sns.pointplot(data<span class="op">=</span>votes_by_barbie, x <span class="op">=</span> <span class="st">"age"</span>, y <span class="op">=</span> <span class="st">"barbie"</span>, hue <span class="op">=</span> <span class="st">"is_male"</span>, ax<span class="op">=</span>ax)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>new_ticks <span class="op">=</span> [i.get_text() <span class="cf">for</span> i <span class="kw">in</span> ax.get_xticklabels()]</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>ax.set_xticks(<span class="bu">range</span>(<span class="dv">0</span>, <span class="bu">len</span>(new_ticks), <span class="dv">10</span>), new_ticks[::<span class="dv">10</span>])</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Preferences by Demographics"</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="sampling_files/figure-html/cell-9-output-1.png" class="img-fluid"></p>
</div>
</div>
<ul>
<li>We see that retirees (in Berkeley) tend to watch Oppenheimer.</li>
<li>We also see that residents who identify as non-male tend to prefer Barbie.</li>
</ul>
</section>
<section id="simple-random-sample" class="level4">
<h4 class="anchored" data-anchor-id="simple-random-sample">Simple Random Sample</h4>
<p>Suppose we took a simple random sample (SRS) of the same size as our retiree sample:</p>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="bu">len</span>(convenience_sample)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>random_sample <span class="op">=</span> movie.sample(n, replace <span class="op">=</span> <span class="va">False</span>) <span class="co">## By default, replace = False</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>np.mean(random_sample[<span class="st">"barbie"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>0.5304705672851117</code></pre>
</div>
</div>
<p>This is very close to the actual vote of 0.5302792307692308!</p>
<p>It turns out that we can get similar results with a <strong>much smaller sample size</strong>, say, 800:</p>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">800</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>random_sample <span class="op">=</span> movie.sample(n, replace <span class="op">=</span> <span class="va">False</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the sample average and the resulting relative error</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>sample_barbie <span class="op">=</span> np.mean(random_sample[<span class="st">"barbie"</span>])</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>err <span class="op">=</span> <span class="bu">abs</span>(sample_barbie<span class="op">-</span>actual_barbie)<span class="op">/</span>actual_barbie</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="co"># We can print output with Markdown formatting too...</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> IPython.display <span class="im">import</span> Markdown</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>Markdown(<span class="ss">f"**Actual** = </span><span class="sc">{</span>actual_barbie<span class="sc">:.4f}</span><span class="ss">, **Sample** = </span><span class="sc">{</span>sample_barbie<span class="sc">:.4f}</span><span class="ss">, "</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>         <span class="ss">f"**Err** = </span><span class="sc">{</span><span class="dv">100</span><span class="op">*</span>err<span class="sc">:.2f}</span><span class="ss">%."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<p><strong>Actual</strong> = 0.5303, <strong>Sample</strong> = 0.5225, <strong>Err</strong> = 1.47%.</p>
</div>
</div>
<p>We’ll learn how to choose this number when we (re)learn the Central Limit Theorem later in the semester.</p>
</section>
<section id="quantifying-chance-error" class="level4">
<h4 class="anchored" data-anchor-id="quantifying-chance-error">Quantifying Chance Error</h4>
<p>In our SRS of size 800, what would be our chance error?</p>
<p>Let’s simulate 1000 versions of taking the 800-sized SRS from before:</p>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>nrep <span class="op">=</span> <span class="dv">1000</span>   <span class="co"># number of simulations</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">800</span>       <span class="co"># size of our sample</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>poll_result <span class="op">=</span> []</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, nrep):</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    random_sample <span class="op">=</span> movie.sample(n, replace <span class="op">=</span> <span class="va">False</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    poll_result.append(np.mean(random_sample[<span class="st">"barbie"</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="16">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>sns.histplot(poll_result, stat<span class="op">=</span><span class="st">'density'</span>, ax<span class="op">=</span>ax)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>ax.axvline(actual_barbie, color<span class="op">=</span><span class="st">"orange"</span>, lw<span class="op">=</span><span class="dv">4</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="sampling_files/figure-html/cell-13-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>What fraction of these simulated samples would have predicted Barbie?</p>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>poll_result <span class="op">=</span> pd.Series(poll_result)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>np.<span class="bu">sum</span>(poll_result <span class="op">&gt;</span> <span class="fl">0.5</span>)<span class="op">/</span><span class="dv">1000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="17">
<pre><code>0.955</code></pre>
</div>
</div>
<p>You can see the curve looks roughly Gaussian/normal. Using KDE:</p>
<div class="cell" data-execution_count="18">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>sns.histplot(poll_result, stat<span class="op">=</span><span class="st">'density'</span>, kde<span class="op">=</span><span class="va">True</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="sampling_files/figure-html/cell-15-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
</section>
<section id="multinomial-probabilities" class="level3">
<h3 class="anchored" data-anchor-id="multinomial-probabilities">Multinomial Probabilities</h3>
<p>So far, we’ve obtained a sample from a population, and that gave us the ability to quantify error and bias. <strong>Given the population distribution</strong>, we can compute the probability of us getting a <strong>particular sample</strong>. (In the real world, we almost <strong>never</strong> know the population distribution, but this is a good start!). A special case called <strong>Multinomial Probabilities</strong> arises when we randomly sample with replacement of a <strong>categorical</strong> population.</p>
<p>It’s very common in data science to have an enormous population that we can only afford to sample a relatively small number of individuals from. If the population is <em>huge</em> compared to the sample, then random sampling <em>with</em> and <em>without</em> replacement are <em>pretty much the same</em>.</p>
<p>For example, Suppose there are 10,000 people in a population. Exactly 7,500 of them like Reese’s; the other 2,500 like Snickers. What is the probability that in a random sample of 20, all people like Reese’s?</p>
<ul>
<li>Random Sample Without Replacement (SRS): <span class="math display">\[
  \frac{7500}{10000} * \frac{7499}{99999} * ... * \frac{7482}{9982} * \frac{7481}{9981} \\
   \\ \approx 0.75 * 0.74997 * ... * 0.7495 * 0.7495
   \\ \approx 0.003151
  \]</span></li>
<li>Random Sample With Replacement: <span class="math display">\[(\frac{7500}{10000})^{20}  \approx 0.00317\]</span></li>
</ul>
<p>As you can see, probabilities of sampling with replacement are much easier to compute!</p>
<p>Multinomial probabilities arise when we sample:</p>
<ul>
<li>Uniformly at random, with replacement.</li>
<li>A fixed number (n) times.</li>
<li>From a categorical distribution.</li>
<li>If 2 categories, Binomial</li>
<li>If &gt; 2 categories, Multinomial:</li>
</ul>
<section id="example-marbles" class="level4">
<h4 class="anchored" data-anchor-id="example-marbles">Example: Marbles</h4>
<p>Say we have a bag of marbles where 60% are blue, 30% are green, and 10% are red. We can use NumPy’s <code>np.random.multinomial</code> to simulate random samples <strong>with replacement</strong>.</p>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>marble_probabilities <span class="op">=</span> [<span class="fl">0.60</span>, <span class="fl">0.30</span>, <span class="fl">0.10</span>]</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co"># draw 100 marbels from this bag at random with replacement.</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>np.random.multinomial(<span class="dv">100</span>, marble_probabilities)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="19">
<pre><code>array([58, 27, 15])</code></pre>
</div>
</div>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We can repeat this simulation multiple times, say 5</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>np.random.multinomial(<span class="dv">100</span>, [<span class="fl">0.60</span>, <span class="fl">0.30</span>, <span class="fl">0.10</span>], size<span class="op">=</span><span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<pre><code>array([[53, 33, 14],
       [60, 32,  8],
       [66, 27,  7],
       [60, 27, 13],
       [48, 39, 13]])</code></pre>
</div>
</div>
<p>If we draw 7 marbles from this bag of marbles, how many of each color will we get?</p>
<p>Suppose we get a sample of 4 blue marbles, 2 green marbles, and 1 red marble. What is the probability of getting this sample?</p>
<details>
<summary>
What is P(bgbbbgr)?
</summary>
<p>Use the product rule to determine the probability for a particular order:</p>
$P(bgbbbgr) = 0.6 * 0.3 * 0.6 * 0.6 * 0.6 * 0.3 * 0.1 = (0.6)^4 (0.3)^2 (0.1)^1 $
</details>
<details>
<summary>
What is P(4 blue, 2 green, 1 red)?
</summary>
<p>We use the addition rule and the multiplication rule: * The first term is the # of ways to choose 4 of 7 places to write b, then choose 2 places to write g (the other 1 gets filled with r). * The second term is the probability of this ordered series of b‘s, g ’s, and r’s for a particular outcome (say, Q1).</p>
<p><span class="math display">\[\frac{7!}{4! 2! 1!} (0.6)^4 (0.3)^2 (0.1)^1 \]</span></p>
This is a multinomial probability!
</details>
</section>
<section id="multinomial-probabilities-generalized" class="level4">
<h4 class="anchored" data-anchor-id="multinomial-probabilities-generalized">Multinomial Probabilities: Generalized</h4>
<p>If we are drawing at random with replacement n times, from a population broken into three separate categories (where p1 + p2 + p3 = 1):</p>
<ul>
<li>Category 1, with proportion p1 of the individuals.</li>
<li>Category 2, with proportion p2 of the individuals.</li>
<li>Category 3, with proportion p3 of the individuals.</li>
</ul>
<p>Then, the multinomial probability of drawing k<sub>1</sub> individuals from Category 1, k<sub>2</sub> individuals from Category 2, and k<sub>3</sub> individuals from Category 3 (where k<sub>1</sub> + k<sub>2</sub> + k<sub>3</sub> = n) is</p>
<p><span class="math display">\[\frac{n!}{k_1! k_2! k_3!} p_1 ^ {k_1} p_2 ^ {k_2} p_3 ^ {k_3} \]</span></p>
<p><strong>At no point in this class will you be required to memorize this!</strong> This is just for your own understanding.</p>
</section>
</section>
</section>
<section id="comparing-convenience-sample-and-srs" class="level2">
<h2 class="anchored" data-anchor-id="comparing-convenience-sample-and-srs">Comparing Convenience Sample and SRS</h2>
<p>Suppose that we are trying to run a poll to predict the mayoral election in Bearkeley City (an imaginary city that neighbors Berkeley)m and we took a sample to predict the election outcome by polling all retirees. Even if they answer truthfully, we have a <strong>convenience sample</strong>. How biased would this sample be in predicting the results? While we will not numerically quantify the bias, in this demo we’ll visually show that because of the voter population distribution, any error in our prediction from a retiree sample cannot be simply due to chance:</p>
<p>First, let’s grab a dataset that has every single voter in the Bearkeley (again, this is a fake dataset) and how they <strong>actually</strong> voted in the election. For the purposes of this example, assume: * “High income” indicates a voter is above the median household income, which is $97,834 (actual Berkeley number). * There are only two mayoral candidates: one Democrat and one Republican. * Every registered voter votes in the election for the candidate under their registered party (Dem or Rep).</p>
<div class="cell" data-tags="[]">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>bearkeley <span class="op">=</span> pd.read_csv(<span class="st">"data/bearkeley.csv"</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="co"># create a 1/0 int that indicates democratic vote</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>bearkeley[<span class="st">'vote.dem'</span>] <span class="op">=</span> (bearkeley[<span class="st">'vote'</span>] <span class="op">==</span> <span class="st">'Dem'</span>).astype(<span class="bu">int</span>)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>bearkeley.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>bearkeley.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>actual_vote <span class="op">=</span> np.mean(bearkeley[<span class="st">"vote.dem"</span>])</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>actual_vote</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This is the <strong>actual outcome</strong> of the election. Based on this result, the Democratic candidate would win. However, if we were to only consider retiree voters (a retired person is anyone age 65 and up):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>convenience_sample <span class="op">=</span> bearkeley[bearkeley[<span class="st">'age'</span>] <span class="op">&gt;=</span> <span class="dv">65</span>]</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>np.mean(convenience_sample[<span class="st">"vote.dem"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Based on this result, we would have predicted that the Republican candidate would win! This error is not due to the sample being too small to yield accurate predictions, because there are 359,396 retirees (about 27% of the 1.3 million Bearkeley voters). Instead, there seems to be something larger happening. Let’s visualize the voter preferences of the entire population to see how retirees trend.</p>
<p>Let us aggregate all voters by age and visualize the fraction of Democratic voters, split by income.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.ticker <span class="im">as</span> ticker</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>sns.set_theme(style<span class="op">=</span><span class="st">'darkgrid'</span>, font_scale <span class="op">=</span> <span class="fl">1.5</span>,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>              rc<span class="op">=</span>{<span class="st">'figure.figsize'</span>:(<span class="dv">7</span>,<span class="dv">5</span>)})</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="co"># aggregate all voters by age</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>votes_by_demo <span class="op">=</span> bearkeley.groupby([<span class="st">"age"</span>,<span class="st">"high_income"</span>]).agg(<span class="st">"mean"</span>).reset_index()</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plt.figure()<span class="op">;</span></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>red_blue <span class="op">=</span> [<span class="st">"#bf1518"</span>, <span class="st">"#397eb7"</span>]</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> sns.color_palette(sns.color_palette(red_blue)):</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>    ax <span class="op">=</span> sns.pointplot(data<span class="op">=</span>votes_by_demo, x <span class="op">=</span> <span class="st">"age"</span>, y <span class="op">=</span> <span class="st">"vote.dem"</span>, hue <span class="op">=</span> <span class="st">"high_income"</span>)</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Voting preferences by demographics"</span>)</span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>fig.canvas.draw()</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>new_ticks <span class="op">=</span> [i.get_text() <span class="cf">for</span> i <span class="kw">in</span> ax.get_xticklabels()]<span class="op">;</span></span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>plt.xticks(<span class="bu">range</span>(<span class="dv">0</span>, <span class="bu">len</span>(new_ticks), <span class="dv">10</span>), new_ticks[::<span class="dv">10</span>])<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>From the plot above, we see that retirees in the imaginary city of Bearkeley tend to vote less Democrat, which skewed our predictions from our sample. We also note that high-income voters tend to vote less Democrat (and more Republican).</p>
<p>Let’s compare our biased convenience sample to a simple random sample. Supposing we took an SRS the same size as our retiree sample, we see that we get a result very close to the actual vote:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">## By default, replace = False</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="bu">len</span>(convenience_sample)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>random_sample <span class="op">=</span> bearkeley.sample(n, replace <span class="op">=</span> <span class="va">False</span>)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>np.mean(random_sample[<span class="st">"vote.dem"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This is very close to the actual vote!</p>
<p>We could even get pretty close with a <em>much smaller sample size</em>, say 800:</p>
<p>It turns out that we are pretty close, <strong>much smaller sample size</strong>, say, 800 (we’ll learn how to choose this number when we introduce the Central Limit Theorem):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">800</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>random_sample <span class="op">=</span> bearkeley.sample(n, replace <span class="op">=</span> <span class="va">False</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>np.mean(random_sample[<span class="st">"vote.dem"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To visualize the chance error in an SRS, let’s simulate 1000 samples of the 800-size Simple Random Sample:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>poll_result <span class="op">=</span> []</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>nrep <span class="op">=</span> <span class="dv">1000</span>   <span class="co"># number of simulations</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">800</span>       <span class="co"># size of our sample</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>,nrep):</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    random_sample <span class="op">=</span> bearkeley.sample(n, replace <span class="op">=</span> <span class="va">False</span>)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>    poll_result.append(np.mean(random_sample[<span class="st">"vote.dem"</span>]))</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>sns.histplot(poll_result, stat<span class="op">=</span><span class="st">'density'</span>, kde<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="co"># What fraction of these simulated samples would have predicted Democrat?</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>poll_result <span class="op">=</span> pd.Series(poll_result)</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>np.<span class="bu">sum</span>(poll_result <span class="op">&gt;=</span> <span class="fl">0.5</span>)<span class="op">/</span><span class="dv">1000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>A few observations:</p>
<ul>
<li>The KDE looks roughly Gaussian.</li>
<li>Supposing that we predicted a Democratic winner if 50% of our sample voted Democrat, then just about 4% of our simulated samples would have predicted the election result incorrectly</li>
</ul>
<p>This visualization further justifies why our convenience sample had an error that was not entirely just due to chance. We’ll revisit this notion later in the course.</p>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>Understanding the sampling process is what lets us go from describing the data to understanding the world. Without knowing / assuming something about how the data were collected, there is no connection between the sample and the population. Ultimately, the dataset doesn’t tell us about the world behind the data.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>