
project:
  type: website
  output-dir: docs

website:
  title: "Data 100"
  sidebar:
    title: "Principles and Techniques of Data Science"
    logo: "data100_logo.png"
    style: "docked"
    search: true
    alignment: "center"
    contents:
      - pandas_1/pandas_1.qmd
      - pandas_2/pandas_2.qmd
      - eda/eda.qmd
      - visualization_1/visualization_1.qmd
      - visualization_2/visualization_2.qmd
      - intro_to_modeling/intro_to_modeling.qmd
      - constant_model_loss_transformations/loss_transformations.qmd

format:
  html:
    theme:
      - cosmo
#       - styles.scss
    toc: true
    toc-depth: 5
    callout-icon: false
    css: styles.css



